export const TASK_REGISTER_START = "TASK_REGISTER_START";
export const TASK_REGISTER_COMPLETE = "TASK_REGISTER_COMPLETE";
export const TASK_REGISTER_END = "TASK_REGISTER_END";

export const TASK_OTP_VERIFICATION_START = "TASK_OTP_VERIFICATION_START";
export const TASK_OTP_VERIFICATION_END = "TASK_OTP_VERIFICATION_END";

export const TASK_LOGIN_START = "TASK_LOGIN_START";
export const TASK_LOGIN_END = "TASK_LOGIN_VERIFICATION_END";