export const TASK_REGISTER_START = "TASK_REGISTER_START";
export const TASK_REGISTER_COMPLETE = "TASK_REGISTER_COMPLETE";
export const TASK_REGISTER_END = "TASK_REGISTER_END";

export const TASK_OTP_VERIFICATION_START = "TASK_OTP_VERIFICATION_START";
export const TASK_OTP_VERIFICATION_END = "TASK_OTP_VERIFICATION_END";

export const TASK_LOGIN_START = "TASK_LOGIN_START";
export const TASK_LOGIN_END = "TASK_LOGIN_VERIFICATION_END";

export const TASK_AIRLINE_LOAD_START = "TASK_AIRLINE_LOAD_START";
export const TASK_AIRLINE_LOAD_END = "TASK_AIRLINE_LOAD_END";

export const TASK_COUNTRY_LOAD_START = "TASK_COUNTRY_LOAD_START";
export const TASK_COUNTRY_LOAD_END = "TASK_COUNTRY_LOAD_END";

export const TASK_STATE_LOAD_START = "TASK_STATE_LOAD_START";
export const TASK_STATE_LOAD_END = "TASK_STATE_LOAD_END";

export const TASK_CITY_LOAD_START = "TASK_CITY_LOAD_START";
export const TASK_CITY_LOAD_END = "TASK_CITY_LOAD_END";

export const TASK_CHECKIN_START = "TASK_CHECKIN_START";
export const TASK_CHECKIN_END = "TASK_CHECKIN_END";

export const TASK_FORGOT_PASSWORD_START = "TASK_FORGOT_PASSWORD_START";
export const TASK_FORGOT_PASSWORD_END = "TASK_FORGOT_PASSWORD_END";