export const TASK_REGISTER_START = "TASK_REGISTER_START";
export const TASK_REGISTER_COMPLETE = "TASK_REGISTER_COMPLETE";
export const TASK_REGISTER_END = "TASK_REGISTER_END";

export const TASK_OTP_VERIFICATION_START = "TASK_OTP_VERIFICATION_START";
export const TASK_OTP_VERIFICATION_END = "TASK_OTP_VERIFICATION_END";

export const TASK_LOGIN_START = "TASK_LOGIN_START";
export const TASK_LOGIN_END = "TASK_LOGIN_VERIFICATION_END";

export const TASK_AIRLINE_LOAD_START = "TASK_AIRLINE_LOAD_START";
export const TASK_AIRLINE_LOAD_END = "TASK_AIRLINE_LOAD_END";

export const TASK_COUNTRY_LOAD_START = "TASK_COUNTRY_LOAD_START";
export const TASK_COUNTRY_LOAD_END = "TASK_COUNTRY_LOAD_END";

export const TASK_STATE_LOAD_START = "TASK_STATE_LOAD_START";
export const TASK_STATE_LOAD_END = "TASK_STATE_LOAD_END";

export const TASK_CITY_LOAD_START = "TASK_CITY_LOAD_START";
export const TASK_CITY_LOAD_END = "TASK_CITY_LOAD_END";

export const TASK_CHECKIN_START = "TASK_CHECKIN_START";
export const TASK_CHECKIN_END = "TASK_CHECKIN_END";
export const TASK_REAPPLY_START = "TASK_REAPPLY_START";
export const TASK_REAPPLY_END = "TASK_REAPPLY_END";

export const TASK_FORGOT_PASSWORD_START = "TASK_FORGOT_PASSWORD_START";
export const TASK_FORGOT_PASSWORD_END = "TASK_FORGOT_PASSWORD_END";





// after Login

export const TASK_GET_ALLEVENTS_START = "TASK_GET_ALLEVENTS_START";
export const TASK_GET_ALLEVENTS_END = "TASK_GET_ALLEVENTS_END";
export const TASK_GET_ALLEVENTS_END_ERROR = "TASK_GET_ALLEVENTS_END_ERROR";

export const TASK_GET_JOINED_EVENTS_START = "TASK_GET_JOINED_EVENTS_START";
export const TASK_GET_JOINED_EVENTS_END = "TASK_GET_JOINED_EVENTS_END";
export const TASK_GET_JOINED_EVENTS_END_ERROR = "TASK_GET_JOINED_EVENTS_END_ERROR";

export const TASK_GET_MY_EVENT_START = "TASK_GET_MY_EVENT_START";
export const TASK_GET_MY_EVENT_END = "TASK_GET_MY_EVENT_END";
export const TASK_GET_MY_EVENT_END_ERROR = "TASK_GET_MY_EVENT_END_ERROR";

export const TASK_DELETE_EVENT_START = "TASK_DELETE_EVENT_START";
export const TASK_DELETE_EVENT_END = "TASK_DELETE_EVENT_END";

export const TASK_JOIN_EVENT_START = "TASK_JOIN_EVENT_START";
export const TASK_JOIN_EVENT_END = "TASK_JOIN_EVENT_END";

export const TASK_LEAVE_EVENT_START = "TASK_LEAVE_EVENT_START";
export const TASK_LEAVE_EVENT_END = "TASK_LEAVE_EVENT_END";

export const TASK_CREATE_EVENT_START = "TASK_CREATE_EVENT_START";
export const TASK_CREATE_EVENT_END = "TASK_CREATE_EVENT_END";

export const TASK_UPDATE_EVENT_START = "TASK_UPDATE_EVENT_START";
export const TASK_UPDATE_EVENT_END = "TASK_UPDATE_EVENT_END";
export const TASK_UPDATE_EVENT_ERROR = "TASK_UPDATE_EVENT_ERROR";

export const TASK_GET_PROFILE_DETAIL_START = "TASK_GET_PROFILE_DETAIL_START";
export const TASK_GET_PROFILE_DETAIL_END = "TASK_GET_PROFILE_DETAIL_END";
export const TASK_GET_PROFILE_DETAIL_ERROR = "TASK_GET_PROFILE_DETAIL_ERROR";